### PR TITLE
Add missing android installation instructions

### LINKED ISSUE #61: App crashes when using ar on Android device.
There was no problem when I built and executed the Android environment for using viroreact in my existing project. 
Afterwards, to run the code in App.js of the starter-kit, I imported only the code into my project and ran it, but there is no error log, and the app keeps forcibly shutting down. 
Can you come up with a solution for this part? Minimum sdk is set. Is there anything else I should do?

### PR DESCRIPTION
**Pull request by robertjcolley**
Updates the starter kit for android. I must have missed this while updating the starter kits! Sorry everyone 😄 

TODO
- [ ] Update [documentation](https://viro-community.readme.io/docs/installation-instructions#6-in-your-androidappsrcmainandroidmanifestxml)

Closes #61

### CODE REVIEW

**Comment by deepak-jha-kgp** [comment]
Crashed on Android Emulator. Could be this -> https://github.com/viromedia/viro/issues/269

**Comment by deepak-jha-kgp** [comment]
App does not crash on physical Android Device but getting a black screen. Seems camera tracking is unavailable. Device is Oneplus 9R, app has required permissions.

**Comment by agallardoysla** [comment]
we need to add: ` <uses-feature android:name="android.hardware.camera.ar" />`

**Comment by robertjcolley** [comment]
> we need to add: ` <uses-feature android:name="android.hardware.camera.ar" />`

Adding this got things working?

> Crashed on Android Emulator. Could be this -> https://github.com/viromedia/viro/issues/269

We don't support the android emulator at the moment, although it is in the roadmap to support.

**Comment by GLandres** [comment]
@robertjcolley yes, this fix Black screen. But I have a crashsing bug with imagenTracking function (android)

**Comment by robertjcolley** [comment]
> @robertjcolley yes, this fix Black screen. But I have a crashsing bug with imagenTracking function (android)

Are you using the App.tsx that comes with the starter kit? Or have you started building with the project?

**Comment by robertjcolley** [comment]
> > @robertjcolley yes, this fix Black screen. But I have a crashsing bug with imagenTracking function (android)
> 
> @agallardoysla Are you using the App.tsx that comes with the starter kit? Or have you started building with the project?

**Comment by GLandres** [comment]
@robertjcolley thanks for your answer. is starterkit, I added a simple imageTracking.

**Comment by robertjcolley** [comment]
> @robertjcolley thanks for your answer. is starterkit, I added a simple imageTracking.

Gotcha. It sounds like that's a separate issue. This PR is to fix the issue with the starter kit "out of the box." I encourage you to create an issue in [ViroReact](https://github.com/NativeVision/viro/issues) with a small example, if possible. I've got a bunch of stability issues to sort through right now and I can add that to the list for the next patch release with your help! 😄

**Comment by rajamuthukumaran-geekyants** [comment]
> we need to add: ` <uses-feature android:name="android.hardware.camera.ar" />`

Hi @robertjcolley @agallardoysla, I tried this but I am still getting black screen on my physical device Samsung Tab S7+ which is an ARCore-supported device and has required permission. However, I didn't see any error in the console. In the past, I only experienced this issue in non-ARCore-supported devices.

**Comment by KowalewskiPawel** [comment]
> > we need to add: ` <uses-feature android:name="android.hardware.camera.ar" />`
> 
> Hi @robertjcolley @agallardoysla, I tried this but I am still getting black screen on my physical device Samsung Tab S7+ which is an ARCore-supported device and has required permission. However, I didn't see any error in the console. In the past, I only experienced this issue in non-ARCore-supported devices.

The same here on Nothing Phone 1, tried various setups, configs, available in this repo but nothing worked out. It's always a black screen.

**Pull request closed without merging**
